//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agendas
    {
        public int Id_Agenda { get; set; }
        public int Id_Deptos { get; set; }
        public System.DateTime Dt_Agenda { get; set; }
        public string Evento { get; set; }
        public string Desc_Agenda { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
    }
}
