//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dizimos
    {
        public int Id_Dizimo { get; set; }
        public int Id_Memb { get; set; }
        public System.DateTime Mes_Ref { get; set; }
        public System.DateTime Dt_Mov { get; set; }
        public decimal Vl_Dizimo { get; set; }
    
        public virtual Membros Membros { get; set; }
    }
}
