//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lancamentos
    {
        public string Id_Lanc { get; set; }
        public Nullable<int> Id_Deptos { get; set; }
        public Nullable<int> Id_Deptos_Receber { get; set; }
        public Nullable<int> Id_Tp_Lanc { get; set; }
        public string Tpo_Mov { get; set; }
        public string Tpo_pag { get; set; }
        public decimal Vl_Lanc { get; set; }
        public string Desc_Lanc { get; set; }
        public Nullable<int> Qtd_Parc_Lanc { get; set; }
        public System.DateTime Dt_Lanc { get; set; }
        public Nullable<System.DateTime> Dt_Mov { get; set; }
        public Nullable<System.DateTime> Dt_Venc { get; set; }
        public string Obs { get; set; }
        public string Faturado { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Departamentos Departamentos1 { get; set; }
        public virtual Tipos_Lancamentos Tipos_Lancamentos { get; set; }
    }
}
