//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Membros
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Membros()
        {
            this.Disciplinas = new HashSet<Disciplinas>();
            this.Dizimos = new HashSet<Dizimos>();
            this.Memb_Depto = new HashSet<Memb_Depto>();
            this.Memb_Familiares = new HashSet<Memb_Familiares>();
            this.Memb_Familiares1 = new HashSet<Memb_Familiares>();
        }
    
        public int Id_Membros { get; set; }
        public int Id_Cargo { get; set; }
        public int Id_Status { get; set; }
        public string Nome { get; set; }
        public string Mae { get; set; }
        public string Pai { get; set; }
        public string Sexo { get; set; }
        public string Matricula { get; set; }
        public System.DateTime Dt_Nasc { get; set; }
        public System.DateTime Dt_Desde { get; set; }
        public Nullable<bool> Ativo { get; set; }
        public string Tel1 { get; set; }
        public string Tel2 { get; set; }
        public string Tel3 { get; set; }
        public string Email { get; set; }
        public string Cep { get; set; }
        public string Rua { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string Uf { get; set; }
        public Nullable<int> N_Casa { get; set; }
        public string Foto { get; set; }
        public string Obs { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Disciplinas> Disciplinas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dizimos> Dizimos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memb_Depto> Memb_Depto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memb_Familiares> Memb_Familiares { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Memb_Familiares> Memb_Familiares1 { get; set; }
        public virtual Status Status { get; set; }
    }
}
