//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Memb_Depto
    {
        public int Id_Memb { get; set; }
        public int Id_Deptos { get; set; }
        public System.DateTime Dt_Ini { get; set; }
        public Nullable<System.DateTime> Dt_Fim { get; set; }
        public string Lider { get; set; }
        public Nullable<bool> Ativo { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual Membros Membros { get; set; }
    }
}
