//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    [Table("Memb_Depto")]
    public partial class MembroDepto
    {
        [Key]
        public int Id_Memb { get; set; }
        [Required(ErrorMessage = "Campo não pode ser nulo.")]
        public int Id_Deptos { get; set; }
        public DateTime Dt_Ini { get; set; }
        public DateTime Dt_Fim { get; set; }
        [DefaultValue(true)]
        public bool Lider { get; set; }
        [DefaultValue(true)]
        public bool Ativo { get; set; }

        public virtual Departamento Departamentos { get; set; }
        public virtual Membro Membros { get; set; }
    }
}
