//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebChurchManagement.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WebChurchManagementDBEntities : DbContext
    {
        public WebChurchManagementDBEntities()
            : base("name=WebChurchManagementDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agendas> Agendas { get; set; }
        public virtual DbSet<Cargos> Cargos { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<Disciplinas> Disciplinas { get; set; }
        public virtual DbSet<Dizimos> Dizimos { get; set; }
        public virtual DbSet<Lancamentos> Lancamentos { get; set; }
        public virtual DbSet<Memb_Depto> Memb_Depto { get; set; }
        public virtual DbSet<Memb_Familiares> Memb_Familiares { get; set; }
        public virtual DbSet<Membros> Membros { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Tipos_Lancamentos> Tipos_Lancamentos { get; set; }
        public virtual DbSet<Visitantes> Visitantes { get; set; }
    }
}
